### ISSUE TITLE
TLTableViewController doesn't configure cells correctly under iOS 8

### ISSUE THREAD

**Issue by fatuhoku** [wtmoose/TLIndexPathTools#36]
Demo project showing broken cell here: https://github.com/fatuhoku/Demo-TLIndexPathTools-Tables-Broken-Under-iOS8/tree/develop. Tested on Simulator, iPad Air (iOS 8).

Two symptoms:

 - text labels for default styles of `UITableViewCell` (Basic, Left / Right Detail, Subtitle) are misplaced ![ios simulator screen shot 2 sep 2014 17 51 20](https://cloud.githubusercontent.com/assets/430233/4122141/9079149e-32c1-11e4-8697-e3bb0f9b2cff.png)
 - custom styles cause cells to overlap ![ios simulator screen shot 2 sep 2014 17 54 28](https://cloud.githubusercontent.com/assets/430233/4122205/2c8933f0-32c2-11e4-94dc-90fe42478bbf.png)

The provided demo project covers the first case.

Using `UITableViewController` and explicitly wiring it up with `TLIndexPathController` still works.

**Comment by wtmoose** [comment]
Workaround published in 0.3.10. Demonstrated in Settings example project. Comment from Settings project:

> In previous versions of TLTableViewController, the logic for heightForRowAtIndexPath
 would in certain scenarios dequeue a cell from the storyboard and return that cell's
 height. This case is problematic with new storyboards that use size classes because
 the dequeued cells have zero height. The new version of heightForRowAtIndexPath
 detects this case and returns UITableViewAutomaticDimension instead of zero, which
 falls back (or perhaps forward) to the new auto sizing cell behavior.
 
> Note that UITableViewAutomaticDimension appears to have some animation issues. In
 particular, the cells below the "volume" cell visibly jump when the "volume" cell
 appears. I assume this is related to the cell being taller than the other cells
 and the UITableViewAutomaticDimension behavior setting up the animations with
 starting values based on the default cell height. The workaround for this issue
 was to make the "volume" cell and instance of TLDynamicHeightCell, which causes
 TLTableViewController's classic cell height calculation to kick in.
